title: "ORLA*"
# author:
#   name: "Kai Gao, Yan Ding, Shiqi Zhang, Jingjin Yu"
#   email: "kg627[AT]scarletmail.rutgers.edu"
{% if site.author %}  
  <p>Name: {{ site.author.name }}</p>  
  <p>Email: {{ site.author.email }}</p>  
{% endif %}
description: "Mobile Manipulator-Based Object Rearrangement with Lazy A*"
theme: minima # or any other theme you'd like to use
